apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: three-tier-application
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP

