apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: signup-login-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000            # Cluster-internal port
      targetPort: 3000      # Container port (backend)
  type: ClusterIP
