apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: signup-login-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5000              # Internal port (service level)
      targetPort: 5000        # Container port (your app runs on 5000)
  type: ClusterIP