apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: signup-login-ingress
  namespace: signup-login-app
spec:
  rules:
    - http:
        paths:
          - path: /signup
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000

          - path: /login
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000

          - path: /add
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
          
          - path: /show
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 5000
