apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: three-tier-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dattarahegaonkar09/backend-of-3-tier-application
        ports:
        - containerPort: 3500
        env:
        - name: PORT
          value: "3500"
        - name: MONGO_CONN_STR
          value: "mongodb://mongodb:27017/todo"
        
